"""Public command/result contract for the common matching engine."""

from .facade import (
    CATALOG_SEARCH_POLICY_VERSION,
    MATCHING_ENGINE_COMMAND_V1,
    MATCHING_ENGINE_COMMAND_V1_1,
    MATCHING_ENGINE_RESULT_V1,
    MATCHING_ENGINE_RESULT_V1_1,
    MATCHING_ENGINE_VERSION,
    REASON_CLAIM_POLICY_VERSION,
    CatalogSearchScoreResult,
    CatalogSearchSignals,
    ExcludedCandidateResult,
    MatchingCandidateCommand,
    MatchingEngineCommand,
    MatchingEngineResult,
    MatchingEngineValidationError,
    MatchingMode,
    RankedCandidateResult,
    ReasonClaim,
    derive_directional_reason_claims,
    derive_reciprocal_reason_claims,
    execute_matching,
    score_catalog_search,
)

__all__ = [
    "CATALOG_SEARCH_POLICY_VERSION",
    "MATCHING_ENGINE_COMMAND_V1",
    "MATCHING_ENGINE_COMMAND_V1_1",
    "MATCHING_ENGINE_RESULT_V1",
    "MATCHING_ENGINE_RESULT_V1_1",
    "MATCHING_ENGINE_VERSION",
    "REASON_CLAIM_POLICY_VERSION",
    "CatalogSearchScoreResult",
    "CatalogSearchSignals",
    "ExcludedCandidateResult",
    "MatchingCandidateCommand",
    "MatchingEngineCommand",
    "MatchingEngineResult",
    "MatchingEngineValidationError",
    "MatchingMode",
    "RankedCandidateResult",
    "ReasonClaim",
    "derive_directional_reason_claims",
    "derive_reciprocal_reason_claims",
    "execute_matching",
    "score_catalog_search",
]
